version: "3.8"

services:
  db:
    image: postgres:13.0
    restart: always
    ports:
      - 5433:5432
    volumes:
      - ./dev/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: fantasydbuser
      POSTGRES_DB: fantasy_hub_development

  app:
    build:
      context: .
      target: dev
    command: bash -c "bin/drun.sh"
    depends_on:
      - db
    ports:
      - 3010:3000
    volumes:
      - .:/usr/src/app
    environment:
      RAILS_ENV: development
      DATABASE_NAME: fantasy_hub_development
      DATABASE_USERNAME: fantasydbuser
      DATABASE_PASSWORD: password
      DATABASE_HOST: db

networks:
  default:
    name: fantasy-nw
